# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/shared/v1/shared.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


class Status(betterproto.Enum):
    STATUS_ONLINE = 0
    STATUS_OFFLINE = 1


@dataclass(eq=False, repr=False)
class Application(betterproto.Message):
    name: str = betterproto.string_field(1)
    status: "Status" = betterproto.enum_field(2)
